version: 2.1

# Use the Python orb for simplified Python setup
orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    # Use Python 3.11 for better compatibility
    docker:
      - image: cimg/python:3.11
    
    steps:
      - checkout  # Checkout source code to working directory
      
      # Navigate to project folder and install Python dependencies
      - run:
          name: Install Python dependencies
          command: |
            cd githubApi567_HW03a
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      
      # Install additional testing dependencies
      - run:
          name: Install test dependencies
          command: |
            cd githubApi567_HW03a
            pip install pytest pytest-cov pytest-html
      
      # Run tests with coverage
      - run:
          name: Run GitHub API tests
          command: |
            cd githubApi567_HW03a
            python -m pytest test_github_api.py -v --tb=short --cov=github_api --cov-report=html --cov-report=term --html=test-report.html --self-contained-html
      
      # Test main function execution
      - run:
          name: Test main function execution
          command: |
            cd githubApi567_HW03a
            python -c "from github_api import get_user_repos_with_commits; print('Function imported successfully')"
      
      # Store test results and coverage reports
      - store_artifacts:
          path: githubApi567_HW03a/test-report.html
          destination: test-report.html
      
      - store_artifacts:
          path: githubApi567_HW03a/htmlcov
          destination: coverage-report
      
      - store_test_results:
          path: githubApi567_HW03a/test-results

  # Test with multiple Python versions
  test-python-versions:
    parameters:
      python-version:
        type: string
        default: "3.11"
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd githubApi567_HW03a
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest pytest-cov
      - run:
          name: Run tests
          command: |
            cd githubApi567_HW03a
            python -m pytest test_github_api.py -v --cov=github_api

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
      # Test multiple Python versions
      - test-python-versions:
          matrix:
            parameters:
              python-version: ["3.9", "3.10", "3.11", "3.12"]
